In [1]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [28]:
df = pd.read_csv('iris.csv')

In [29]:
df.head()

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [30]:
df = df.rename(columns = {'variety' : 'target'})

In [31]:
df.head()

   sepal.length  sepal.width  petal.length  petal.width  target
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [32]:
dic = {'Setosa' : 0.0, 'Versicolor' : 1.0,'Virginica':2.0 }

In [33]:
df['target'] = df['target'].map(dic)

In [34]:
df.head()

   sepal.length  sepal.width  petal.length  petal.width  target
0           5.1          3.5           1.4          0.2     0.0
1           4.9          3.0           1.4          0.2     0.0
2           4.7          3.2           1.3          0.2     0.0
3           4.6          3.1           1.5          0.2     0.0
4           5.0          3.6           1.4          0.2     0.0

In [35]:
df.shape

(150, 5)

In [36]:
from sklearn.model_selection import train_test_split

In [37]:
features = df.drop('target',axis = 1).values
label = df['target'].values

In [38]:
X_train, X_test, y_train,y_test = train_test_split(features,label, test_size=0.2,random_state=33)

In [39]:
X_train

array([[5.6, 2.7, 4.2, 1.3],
       [6.7, 3.1, 4.7, 1.5],
       [5.6, 2.8, 4.9, 2. ],
       [6.4, 3.2, 5.3, 2.3],
       [6.7, 3.1, 5.6, 2.4],
       [6.7, 3. , 5.2, 2.3],
       [5.8, 2.7, 5.1, 1.9],
       [5.7, 3. , 4.2, 1.2],
       [5. , 2.3, 3.3, 1. ],
       [4.9, 3.1, 1.5, 0.2],
       [6.3, 2.3, 4.4, 1.3],
       [5.8, 2.6, 4. , 1.2],
       [6.2, 2.9, 4.3, 1.3],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.4, 1.4, 0.3],
       [5.1, 2.5, 3. , 1.1],
       [4.8, 3.4, 1.6, 0.2],
       [7.9, 3.8, 6.4, 2. ],
       [5.1, 3.4, 1.5, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.5, 3. , 5.5, 1.8],
       [5.4, 3.9, 1.7, 0.4],
       [7. , 3.2, 4.7, 1.4],
       [5.8, 2.8, 5.1, 2.4],
       [7.7, 2.6, 6.9, 2.3],
       [5.5, 2.5, 4. , 1.3],
       [5.9, 3.2, 4.8, 1.8],
       [4.9, 3.6, 1.4, 0.1],
       [4.5, 2.3, 1.3, 0.3],
       [6.3, 2.8, 5.1, 1.5],
       [4.4, 2.9, 1.4, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [7.2, 3. , 5.8, 1.6],
       [6. , 3.4, 4.5, 1.6],
       [6.2, 2.2, 4.5, 1.5],
       [7.4, 2.8, 6.1, 1.9],
       [6.8, 3. , 5.5, 2.1],
       [6.4, 2.8, 5.6, 2.2],
       [5.7, 2.5, 5. , 2. ],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.8, 1.5, 0.3],
       [6.8, 2.8, 4.8, 1.4],
       [5.2, 2.7, 3.9, 1.4],
       [5.1, 3.8, 1.6, 0.2],
       [5.6, 2.5, 3.9, 1.1],
       [6.1, 3. , 4.9, 1.8],
       [6.6, 2.9, 4.6, 1.3],
       [6.4, 2.8, 5.6, 2.1],
       [4.3, 3. , 1.1, 0.1],
       [7.2, 3.6, 6.1, 2.5],
       [5.1, 3.5, 1.4, 0.2],
       [6.3, 2.5, 4.9, 1.5],
       [4.4, 3.2, 1.3, 0.2],
       [7.6, 3. , 6.6, 2.1],
       [6.4, 3.2, 4.5, 1.5],
       [5.1, 3.8, 1.9, 0.4],
       [6.5, 3.2, 5.1, 2. ],
       [6.3, 2.7, 4.9, 1.8],
       [5. , 3.5, 1.3, 0.3],
       [5.2, 3.4, 1.4, 0.2],
       [6.4, 2.7, 5.3, 1.9],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [4.6, 3.2, 1.4, 0.2],
       [6.9, 3.1, 5.4, 2.1],
       [6.3, 2.9, 5.6, 1.8],
       [5.5, 3.5, 1.3, 0.2],
       [5.7, 2.6, 3.5, 1. ],
       [5. , 3.3, 1.4, 0.2],
       [6. , 2.2, 4. , 1. ],
       [4.9, 3. , 1.4, 0.2],
       [5. , 2. , 3.5, 1. ],
       [6.6, 3. , 4.4, 1.4],
       [5.7, 2.8, 4.5, 1.3],
       [5.5, 2.6, 4.4, 1.2],
       [5.5, 2.3, 4. , 1.3],
       [4.8, 3.1, 1.6, 0.2],
       [6. , 2.9, 4.5, 1.5],
       [5. , 3. , 1.6, 0.2],
       [6.9, 3.1, 4.9, 1.5],
       [6.7, 2.5, 5.8, 1.8],
       [5.3, 3.7, 1.5, 0.2],
       [5.2, 4.1, 1.5, 0.1],
       [5. , 3.4, 1.6, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [7.7, 3.8, 6.7, 2.2],
       [7.3, 2.9, 6.3, 1.8],
       [4.6, 3.1, 1.5, 0.2],
       [5.5, 2.4, 3.7, 1. ],
       [5.8, 2.7, 3.9, 1.2],
       [6.7, 3.3, 5.7, 2.1],
       [5.8, 2.7, 4.1, 1. ],
       [5.4, 3.7, 1.5, 0.2],
       [5. , 3.4, 1.5, 0.2],
       [6. , 2.7, 5.1, 1.6],
       [5.7, 2.8, 4.1, 1.3],
       [6.1, 2.8, 4.7, 1.2],
       [5.1, 3.3, 1.7, 0.5],
       [5.6, 3. , 4.1, 1.3],
       [5.4, 3. , 4.5, 1.5],
       [5.4, 3.9, 1.3, 0.4],
       [6.7, 3.3, 5.7, 2.5],
       [4.9, 2.5, 4.5, 1.7],
       [6.2, 3.4, 5.4, 2.3],
       [5.5, 2.4, 3.8, 1.1],
       [7.7, 2.8, 6.7, 2. ],
       [5.4, 3.4, 1.5, 0.4],
       [6.7, 3. , 5. , 1.7],
       [5.5, 4.2, 1.4, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [4.8, 3. , 1.4, 0.3],
       [5.8, 2.7, 5.1, 1.9],
       [5.9, 3. , 4.2, 1.5],
       [7.1, 3. , 5.9, 2.1],
       [4.9, 2.4, 3.3, 1. ],
       [6.3, 2.5, 5. , 1.9],
       [5.6, 3. , 4.5, 1.5],
       [7.7, 3. , 6.1, 2.3],
       [5.4, 3.4, 1.7, 0.2]])

In [40]:
X_train = torch.FloatTensor(X_train)
X_test = torch.FloatTensor(X_test)

In [44]:
y_train = torch.LongTensor(y_train).reshape(-1,1)
y_test = torch.LongTensor(y_test).reshape(-1,1)

In [46]:
from torch.utils.data import TensorDataset, DataLoader

In [48]:
data = df.drop('target',axis=1).values
labels = df['target'].values

In [49]:
iris = TensorDataset(torch.FloatTensor(data),torch.LongTensor(labels))

In [52]:
# for i in iris:
#     print(i)

In [53]:
iris_loader = DataLoader(iris,batch_size = 50,shuffle=True)

In [55]:
iris_loader

In [54]:
for i_batch, sample_batch in enumerate(iris_loader):
    print(i_batch, sample_batch)

0 [tensor([[6.7000, 3.0000, 5.0000, 1.7000],
        [6.5000, 3.0000, 5.2000, 2.0000],
        [6.9000, 3.1000, 4.9000, 1.5000],
        [4.4000, 3.0000, 1.3000, 0.2000],
        [5.5000, 3.5000, 1.3000, 0.2000],
        [4.8000, 3.1000, 1.6000, 0.2000],
        [7.7000, 3.0000, 6.1000, 2.3000],
        [5.6000, 3.0000, 4.1000, 1.3000],
        [6.0000, 2.9000, 4.5000, 1.5000],
        [4.9000, 3.1000, 1.5000, 0.1000],
        [7.2000, 3.2000, 6.0000, 1.8000],
        [5.0000, 3.4000, 1.6000, 0.4000],
        [6.8000, 3.0000, 5.5000, 2.1000],
        [5.0000, 3.5000, 1.6000, 0.6000],
        [4.7000, 3.2000, 1.6000, 0.2000],
        [5.1000, 3.8000, 1.6000, 0.2000],
        [5.1000, 3.5000, 1.4000, 0.3000],
        [6.6000, 3.0000, 4.4000, 1.4000],
        [5.5000, 2.4000, 3.8000, 1.1000],
        [5.8000, 2.8000, 5.1000, 2.4000],
        [6.0000, 3.0000, 4.8000, 1.8000],
        [6.1000, 3.0000, 4.6000, 1.4000],
        [6.3000, 3.4000, 5.6000, 2.4000],
        [5.4000, 3.9000, 1.7000, 0.4000],
        [6.7000, 3.3000, 5.7000, 2.5000],
        [5.2000, 3.4000, 1.4000, 0.2000],
        [6.0000, 2.2000, 4.0000, 1.0000],
        [7.7000, 2.8000, 6.7000, 2.0000],
        [5.2000, 3.5000, 1.5000, 0.2000],
        [5.5000, 2.4000, 3.7000, 1.0000],
        [6.0000, 2.2000, 5.0000, 1.5000],
        [5.1000, 3.4000, 1.5000, 0.2000],
        [6.7000, 3.1000, 4.7000, 1.5000],
        [5.0000, 3.4000, 1.5000, 0.2000],
        [6.7000, 3.3000, 5.7000, 2.1000],
        [5.7000, 3.0000, 4.2000, 1.2000],
        [4.5000, 2.3000, 1.3000, 0.3000],
        [6.2000, 2.8000, 4.8000, 1.8000],
        [5.6000, 2.8000, 4.9000, 2.0000],
        [5.4000, 3.9000, 1.3000, 0.4000],
        [6.8000, 3.2000, 5.9000, 2.3000],
        [5.6000, 2.9000, 3.6000, 1.3000],
        [5.7000, 2.5000, 5.0000, 2.0000],
        [6.3000, 2.5000, 5.0000, 1.9000],
        [4.8000, 3.0000, 1.4000, 0.3000],
        [5.8000, 2.7000, 4.1000, 1.0000],
        [6.2000, 2.2000, 4.5000, 1.5000],
        [6.7000, 3.0000, 5.2000, 2.3000],
        [5.0000, 3.6000, 1.4000, 0.2000],
        [6.3000, 2.8000, 5.1000, 1.5000]]), tensor([1, 2, 1, 0, 0, 0, 2, 1, 1, 0, 2, 0, 2, 0, 0, 0, 0, 1, 1, 2, 2, 1, 2, 0,
        2, 0, 1, 2, 0, 1, 2, 0, 1, 0, 2, 1, 0, 2, 2, 0, 2, 1, 2, 2, 0, 1, 1, 2,
        0, 2])]
1 [tensor([[5.7000, 2.9000, 4.2000, 1.3000],
        [6.9000, 3.1000, 5.4000, 2.1000],
        [5.6000, 2.7000, 4.2000, 1.3000],
        [6.4000, 3.2000, 4.5000, 1.5000],
        [5.1000, 3.3000, 1.7000, 0.5000],
        [6.2000, 2.9000, 4.3000, 1.3000],
        [5.8000, 2.7000, 3.9000, 1.2000],
        [4.9000, 2.4000, 3.3000, 1.0000],
        [6.3000, 3.3000, 4.7000, 1.6000],
        [6.1000, 2.8000, 4.0000, 1.3000],
        [6.3000, 2.9000, 5.6000, 1.8000],
        [6.5000, 2.8000, 4.6000, 1.5000],
        [5.3000, 3.7000, 1.5000, 0.2000],
        [5.0000, 3.5000, 1.3000, 0.3000],
        [5.0000, 3.0000, 1.6000, 0.2000],
        [4.6000, 3.4000, 1.4000, 0.3000],
        [5.0000, 2.0000, 3.5000, 1.0000],
        [6.1000, 2.6000, 5.6000, 1.4000],
        [5.1000, 3.8000, 1.5000, 0.3000],
        [5.8000, 2.7000, 5.1000, 1.9000],
        [6.4000, 3.2000, 5.3000, 2.3000],
        [6.7000, 3.1000, 4.4000, 1.4000],
        [6.5000, 3.2000, 5.1000, 2.0000],
        [4.3000, 3.0000, 1.1000, 0.1000],
        [5.8000, 2.6000, 4.0000, 1.2000],
        [5.0000, 2.3000, 3.3000, 1.0000],
        [5.1000, 3.8000, 1.9000, 0.4000],
        [6.1000, 2.9000, 4.7000, 1.4000],
        [6.1000, 3.0000, 4.9000, 1.8000],
        [5.5000, 2.6000, 4.4000, 1.2000],
        [6.3000, 2.3000, 4.4000, 1.3000],
        [6.5000, 3.0000, 5.5000, 1.8000],
        [5.7000, 2.8000, 4.1000, 1.3000],
        [5.4000, 3.0000, 4.5000, 1.5000],
        [4.6000, 3.6000, 1.0000, 0.2000],
        [7.2000, 3.6000, 6.1000, 2.5000],
        [6.3000, 2.5000, 4.9000, 1.5000],
        [7.4000, 2.8000, 6.1000, 1.9000],
        [6.8000, 2.8000, 4.8000, 1.4000],
        [5.0000, 3.2000, 1.2000, 0.2000],
        [5.8000, 4.0000, 1.2000, 0.2000],
        [4.9000, 2.5000, 4.5000, 1.7000],
        [5.4000, 3.4000, 1.5000, 0.4000],
        [5.2000, 2.7000, 3.9000, 1.4000],
        [6.4000, 3.1000, 5.5000, 1.8000],
        [5.9000, 3.2000, 4.8000, 1.8000],
        [6.0000, 2.7000, 5.1000, 1.6000],
        [5.7000, 4.4000, 1.5000, 0.4000],
        [5.9000, 3.0000, 5.1000, 1.8000],
        [4.6000, 3.1000, 1.5000, 0.2000]]), tensor([1, 2, 1, 1, 0, 1, 1, 1, 1, 1, 2, 1, 0, 0, 0, 0, 1, 2, 0, 2, 2, 1, 2, 0,
        1, 1, 0, 1, 2, 1, 1, 2, 1, 1, 0, 2, 1, 2, 1, 0, 0, 2, 0, 1, 2, 1, 1, 0,
        2, 0])]
2 [tensor([[4.9000, 3.6000, 1.4000, 0.1000],
        [4.7000, 3.2000, 1.3000, 0.2000],
        [6.2000, 3.4000, 5.4000, 2.3000],
        [6.6000, 2.9000, 4.6000, 1.3000],
        [4.4000, 2.9000, 1.4000, 0.2000],
        [6.9000, 3.1000, 5.1000, 2.3000],
        [6.4000, 2.7000, 5.3000, 1.9000],
        [4.8000, 3.4000, 1.6000, 0.2000],
        [5.1000, 3.7000, 1.5000, 0.4000],
        [4.9000, 3.1000, 1.5000, 0.2000],
        [5.6000, 2.5000, 3.9000, 1.1000],
        [6.4000, 2.8000, 5.6000, 2.2000],
        [5.5000, 2.5000, 4.0000, 1.3000],
        [5.8000, 2.7000, 5.1000, 1.9000],
        [6.7000, 3.1000, 5.6000, 2.4000],
        [6.4000, 2.8000, 5.6000, 2.1000],
        [6.3000, 3.3000, 6.0000, 2.5000],
        [6.9000, 3.2000, 5.7000, 2.3000],
        [5.1000, 3.5000, 1.4000, 0.2000],
        [5.7000, 2.8000, 4.5000, 1.3000],
        [5.6000, 3.0000, 4.5000, 1.5000],
        [4.6000, 3.2000, 1.4000, 0.2000],
        [6.1000, 2.8000, 4.7000, 1.2000],
        [6.7000, 2.5000, 5.8000, 1.8000],
        [5.4000, 3.7000, 1.5000, 0.2000],
        [7.3000, 2.9000, 6.3000, 1.8000],
        [5.4000, 3.4000, 1.7000, 0.2000],
        [4.4000, 3.2000, 1.3000, 0.2000],
        [4.8000, 3.0000, 1.4000, 0.1000],
        [7.6000, 3.0000, 6.6000, 2.1000],
        [5.7000, 3.8000, 1.7000, 0.3000],
        [5.5000, 2.3000, 4.0000, 1.3000],
        [7.7000, 2.6000, 6.9000, 2.3000],
        [4.9000, 3.0000, 1.4000, 0.2000],
        [7.0000, 3.2000, 4.7000, 1.4000],
        [5.5000, 4.2000, 1.4000, 0.2000],
        [4.8000, 3.4000, 1.9000, 0.2000],
        [6.3000, 2.7000, 4.9000, 1.8000],
        [5.7000, 2.6000, 3.5000, 1.0000],
        [5.1000, 2.5000, 3.0000, 1.1000],
        [7.9000, 3.8000, 6.4000, 2.0000],
        [6.0000, 3.4000, 4.5000, 1.6000],
        [6.4000, 2.9000, 4.3000, 1.3000],
        [7.7000, 3.8000, 6.7000, 2.2000],
        [5.0000, 3.3000, 1.4000, 0.2000],
        [7.2000, 3.0000, 5.8000, 1.6000],
        [5.9000, 3.0000, 4.2000, 1.5000],
        [7.1000, 3.0000, 5.9000, 2.1000],
        [6.5000, 3.0000, 5.8000, 2.2000],
        [5.2000, 4.1000, 1.5000, 0.1000]]), tensor([0, 0, 2, 1, 0, 2, 2, 0, 0, 0, 1, 2, 1, 2, 2, 2, 2, 2, 0, 1, 1, 0, 1, 2,
        0, 2, 0, 0, 0, 2, 0, 1, 2, 0, 1, 0, 0, 2, 1, 1, 2, 1, 1, 2, 0, 2, 1, 2,
        2, 0])]